### ISSUE TITLE
New Sort logo suggestion

### ISSUE THREAD

**Issue by aaaberg** [chrisdl/nova-sort#6]
# Description
I humbly submit this logo to be used for `Sort` on the Nova Extensions page.

### Mockup in context
![nova-icons-mockup](https://user-images.githubusercontent.com/31449101/101998691-c0a71800-3c92-11eb-8c7d-8c9f6d46ef9b.png)

### Full resolution image file
![Sort](https://user-images.githubusercontent.com/31449101/101998640-51312880-3c92-11eb-8228-a84ce8851f34.png)

**Comment by chrisdl** [comment]
^^ Nice! Thanks!
